# Generated by Django 4.1.7 on 2023-03-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtextfile',
            name='textfile',
            field=models.FileField(upload_to='userfiles/', verbose_name='wert'),
        ),
    ]
