# Generated by Django 4.1.7 on 2023-03-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_mtextfile_textfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtextfile',
            name='textfile',
            field=models.FileField(upload_to='userfiles/', verbose_name='Выберите файл'),
        ),
    ]
