# Generated by Django 4.2.1 on 2023-05-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_letter_letter_black_alter_letter_letter_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='games/voice'),
        ),
    ]
