# Generated by Django 4.2.1 on 2023-05-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_letter_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='letter_black',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='letter_color',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='letter_outline',
        ),
    ]
