# Generated by Django 4.2.1 on 2023-05-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_remove_letter_letter_black_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='letters',
            field=models.ManyToManyField(to='games.letter'),
        ),
    ]
